[package]
name = "steviegoodman/voxel-game"
description = "Voxel game created on the roblox platform."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Cmdr = "evaera/cmdr@1.12.0"
Courier = "steviegoodman/courier@0.1.0"
Trove = "sleitnick/trove@1.5.0"